### ISSUE TITLE
Computer task sound needs to be changed to something more appropriate

### ISSUE THREAD

**Issue by MasterOfCubesAU** [MasterOfCubesAU/CrushDepth#72]

**Comment by Jer-Tran** [comment]
Also, I think the weird thump sound on startup is a misplay of the computer task sound. Not certain though

**Comment by MasterOfCubesAU** [comment]
> Also, I think the weird thump sound on startup is a misplay of the computer task sound. Not certain though

Yea this is correct. I don't believe we have found the source of the problem weirdly enough. Need to take a deeper look today.
