### ISSUE TITLE
Fire extinguisher starts on the floor

### ISSUE THREAD

**Issue by MasterOfCubesAU** [MasterOfCubesAU/CrushDepth#85]
For some reason it spawns on the floor (only at first launch)
![image](https://github.com/MasterOfCubesAU/CrushDepth/assets/38149391/2131f712-bf2b-4e90-9c8c-14f2335e3313)

**Comment by Jer-Tran** [comment]
Known issue, due to the way the mesh is, the gravity is a bit messy
On item respawn the items have no physics, which is why they aren't a problem then
